spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:shboard-test;MODE=Mysql

  h2:
    console:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 3

